const ITEM_FETCH_START = 'ITEM_FETCH_START';
const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS';
const ITEM_FETCH_ERROR = 'ITEM_FETCH_ERROR';
const SEARCH_FETCH_START = 'SEARCH_FETCH_START';
const SEARCH_FETCH_SUCCESS = 'SEARCH_FETCH_SUCCESS';
const SEARCH_FETCH_ERROR = 'SEARCH_FETCH_ERROR';
const ADD_BREADCRUMBS = 'ADD_BREADCRUMBS';

export {
    ITEM_FETCH_START,
    ITEM_FETCH_SUCCESS,
    ITEM_FETCH_ERROR,
    SEARCH_FETCH_START,
    SEARCH_FETCH_SUCCESS,
    SEARCH_FETCH_ERROR,
    ADD_BREADCRUMBS
};

export default {
    ITEM_FETCH_START,
    ITEM_FETCH_SUCCESS,
    ITEM_FETCH_ERROR,
    SEARCH_FETCH_START,
    SEARCH_FETCH_SUCCESS,
    SEARCH_FETCH_ERROR,
    ADD_BREADCRUMBS
};
